version: '3.8'

services:
  app:
    image: 'springboot_microservice:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/XWSUsersDB
      - SPRING_DATASOURCE_USERNAME=bajo
      - SPRING_DATASOURCE_PASSWORD=bajo
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=bajo
      - POSTGRES_PASSWORD=bajo