version: "3.8"
services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8081:8080
    networks:
      - backend
    volumes:
      - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./Gateway/api_conf.d:/etc/nginx/api_conf.d
      - ./Gateway/api_backends.conf:/etc/nginx/api_backends.conf
      - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
      - ./Gateway/api_json_errors.conf:/etc/nginx/api_json_errors.conf
      

  test-service:
    build:
      context: ./GoLangMicroservice
      dockerfile: Dockerfile
    networks:
          - backend

networks:
  backend:
    name: nistagram
    driver: bridge